[project]
name = "tcp-ip-simulation"
version = "0.2.2"
description = "Generates materials for a classroom simulation of TCP/IP"
authors = [
    {name = "Chris Proctor",email = "chris@chrisproctor.net"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2 (>=3.1.6,<4.0.0)",
    "networkx (>=3.5,<4.0)",
    "matplotlib (>=3.10.7,<4.0.0)"
]

[project.urls]
homepage = "https://github.com/cproctor/tcp-ip-simulation"
repository = "https://github.com/cproctor/tcp-ip-simulation"

[project.scripts]
generate-tcp-ip-simulation = "tcp_ip_simulation.cli:generate"

[build-system]
requires = ["uv_build>=0.8,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
source-include = ["sample-tcp-ip-simulation.pdf"]
